// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALgKlWop5pKFUcKaoaQDbkJqAr176mTxM',
    appId: '1:963166292182:web:d7fc4255b11780150ba177',
    messagingSenderId: '963166292182',
    projectId: 'chatfirebase-5c025',
    authDomain: 'chatfirebase-5c025.firebaseapp.com',
    storageBucket: 'chatfirebase-5c025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPmoc5pjaCqkx1SK5vFpn0ZR8sBTWkuBY',
    appId: '1:963166292182:android:4abbf433806957820ba177',
    messagingSenderId: '963166292182',
    projectId: 'chatfirebase-5c025',
    storageBucket: 'chatfirebase-5c025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsiSNpjRv7NRlEulsPXPzwi09i6vKPZvI',
    appId: '1:963166292182:ios:114f0909db156a3d0ba177',
    messagingSenderId: '963166292182',
    projectId: 'chatfirebase-5c025',
    storageBucket: 'chatfirebase-5c025.appspot.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsiSNpjRv7NRlEulsPXPzwi09i6vKPZvI',
    appId: '1:963166292182:ios:114f0909db156a3d0ba177',
    messagingSenderId: '963166292182',
    projectId: 'chatfirebase-5c025',
    storageBucket: 'chatfirebase-5c025.appspot.com',
    iosBundleId: 'com.example.mysite',
  );
}
